# Generated by Django 4.1 on 2023-10-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phoneno',
        ),
    ]
