# Generated by Django 4.0.4 on 2022-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_outdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='outdesc',
            field=models.CharField(max_length=1000),
        ),
    ]
