# Generated by Django 4.1 on 2023-10-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_outdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank='True', default='', upload_to='shop/images'),
        ),
    ]
